[package]
name = "sandbloodwater"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
bevy_embedded_assets = "0.9.1"
tsv = "0.1.1"
wasm-bindgen-cli = "0.2.89"
