[alias]
build-release = "build --release"
build-wasm = "build --release --target wasm32-unknown-unknown"
release-web = "wasm-bindgen --out-dir ./target/release/web --target web --no-typescript ./target/wasm32-unknown-unknown/release/sandbloodwater.wasm"
